global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # PetStar 애플리케이션
  - job_name: 'petstar'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['43.200.83.214:8080']
    scrape_interval: 10s
